language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=develop
  - secure: gUt9W9QFrIfoiZwuL3ID5He07SdCc09A5OFaXvu4iLT/tx22AmhLCoKA3tohZ/CwNOJCv5JA9KT80JUVyRWXkghao/8uWDHu47yQ+VHqWXc1M5jfox0lBzSVhVDmconuUhKP0cu27iNVM0fwEXMMgz+x5J387BCnWy4xRJYAyybaqiOfxwyt++q87vwIANMhYNKaikrryXxRYJHTHAL1+600dzUWoFPRxtUliI/4O4hCtnurM77oz8PtE2bXrZb0enFSS6DeL0lgknbNyp26Av3DJKgY2YfNWVXWnuBxwRB9NxaVh+MFa3XpbrmJE1SBNO+NH50o5+bLf06T//v2ewc6VHJZLZfDQCjKOxavDPFAU4aSlyWcpYnbaq3Qh1/17uI4HMc59x3gIXrGIgT6grkwfX6QmSFJFtdLwC4M0Og+oBPjqrJfm8oVJtEFtIMK34LwfRhvLoalqY+KZyDnoTUDC4GLvHvv0p8OktIiK0nh9hQSe4WCkZm4rqg+9ccbUzOBAOTQdDoiR2neTT1aEoP599IqLoGG9ynMD94fFTRIcigyTRwcBSKd/Nc549cbs0TajEBcGcuXrCOEz+JaCMS3aTSZb/sM8VLHK+ke2d0vxnIrVBg/sA9gdzTXVvs6ttfVIuB1Vy1A17J3rYc3GE5IG12b63CLr5wUj0ceWf4=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
  - bundle/cache
before_install:
- rvm install 2.1
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
