language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=develop
  - secure: JYnT1mZMLHWsp6lx9odV00IZeQyFgEFPDvIwPCKMO92/vYvd6TTHCR7E5bM8qaUGrPjELxOCEiiK33CfeWZgJTiP5ay0HQNio7M0BgBnVic/O1MUuO+sIVUu+fxDzmQILD6Hc09NbRfspwT2K/kKe5lfro2yFpsHcreoZcqumdhK0vceU0XDKN5d3RSiyOsyca0xGKiMuvUvTk+pkkPdI6NrPSHkpV1DMj/taZRWCyhw02a097xao18zcwIUVZX75tPKhaUuA+AYPocqN0ihWlF7a1dF4dykU24/ex5jSATKiDMATbjHq1nu4LPJSuTUkE57709eK/ppS9edzFQ3guIlxvyDq6hDo81fbHwAf+5iXJPw+CclJIVrVlLZiww/Fv4JnionyB1tEOi8YpzjR8z2/6n4q83R8dCO5p2dvqC7E7okknvvUGHdWe3jxE6cnJ87txm/6Hial6PL99bxvAumvp/AGiQuBZwRk/vpCbUfFmsBzB2ZdERVAveMsungvFWqP8TzJtLlDzinuWUp0jzSuGH6wdFA+exgomXhXFZ1f/NGXthe83ToOqwOuWWXADExYwdJ9O+2Em/DLdRQsYyFYwxVts5kGBDISeDxyeaD10y6HyxzIhlRsCJqkLfbatmwa5HM/gMQAxTYA/iVo1CkJOOaU4nHF9vhJ5zdhtc=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
  - bundle/cache
before_install:
- rvm install 2.1
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
