# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dylan Moriarty
email: eatincake@gmail.com
description: > # Dylan Moriarty's rad webzone. Cartography! Infographics! Lots of good stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dylanmoriarty.github.io" # the base hostname & protocol for your site
twitter_username: DylanMoriarty
github_username:  DylanMoriarty

timezone: US

# Build settings
markdown: kramdown

# Collections
collections:
  blog:
    output: true
  cakes:
    output: true